
[env]
TERM = "xterm-256color"

[font.normal]
family = "FiraCode Nerd Font Mono"

[terminal.shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window]
startup_mode = "Windowed"
option_as_alt = "OnlyRight"

[window.dimensions]
columns = 145
lines = 45

[general]
import = ["/Users/joakimrosenfeldtpedersen/.config/alacritty/dracula.toml"]

[terminal]
