import = ["/Users/joakimrosenfeldtpedersen/.config/alacritty/dracula.toml"]

[env]
TERM = "xterm-256color"

[font.normal]
family = "FiraCode Nerd Font Mono"

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window]
startup_mode = "Windowed"

[window.dimensions]
columns = 145
lines = 45
